
forge "https://forgeapi.puppetlabs.com"

mod "puppetlabs-stdlib", "4.14.0"
mod "puppetlabs-apt", "2.3.0"
mod "puppetlabs-concat", "2.2.0"
mod "puppetlabs-postgresql", "4.8.0"
mod "puppet-archive", "1.1.2"
mod "puppet-nginx", "0.5.0"
mod "willdurand-nodejs", "1.8.5"
mod "bashtoni-timezone", "1.0.0"
mod "maestrodev-wget", "1.7.3"
mod "maestrodev-maven", "1.4.0"
mod "setup", :local => true
