node {
  stage("Checkout") {
    checkout scm
  }
  stage("Create infrastructure") {

  }
  stage("Provision infrastructure") {

  }
  stage("Test infrastructure") {

  }
  stage("Destroy infrastructure") {
  }
}